### ISSUE TITLE
Display data in correct order, params

### ISSUE THREAD

**Issue by hieulq** [hieulq/pgscm#13]
E.g: all data must be filtered by _deleted_at != null.
Certificate must be filtered MORE by expiry date > current date

**Comment by hieulq** [comment]
@HaManhDong filtered cert by condition: expiry date > current date

**Comment by HaManhDong** [comment]
Sorry, can you give me some example about filter cert by condition: expiry date > current date?

**Comment by hieulq** [comment]
cert A have expiry date in 31/12/2017
cert B have expiry date in 31/5/2017
current date is 14/8/2017
so cert B will be hidden, cert A will be displayed

we will provide some utilities, button to filter/search/query history of cert later.

**Comment by HaManhDong** [comment]
Thank you. I understand. I will fix it and push with ajax for group form together tonight.

**Comment by HaManhDong** [comment]
Done it. I had added the filter expiry date > current date and also displayed certificates have expiry date is NULL.

**Comment by hieulq** [comment]
@HaManhDong thanks, good work!
