### ISSUE TITLE
Dynamic ajax call for all select2 class

### ISSUE THREAD

**Issue by hieulq** [hieulq/pgscm#8]
Need to call ajax for dynamic load content of all select2 class.
For example, click a province select class, choose any province then the district select class will be loaded based on the province id choice.

**Comment by hieulq** [comment]
@HaManhDong pick this issue

**Comment by HaManhDong** [comment]
I had done it. Please close this issue.

**Comment by hieulq** [comment]
@HaManhDong will close after you apply for all form/view
